<script src='third-party/jquery/jquery-1.4.2.min.js' type="text/javascript"></script>    
<script src='third-party/jquery/jquery.tooltip.js' type="text/javascript"></script>
<script src='third-party/jquery/jquery.autocomplete.js' type="text/javascript"></script>
<script src='third-party/jquery/tablesorter-function.js' type="text/javascript"></script>
<script src='third-party/jquery/tablesorter.min.js' type="text/javascript"></script>
<script src='third-party/jquery/tablesorter.pager.js' type="text/javascript"></script>
<script src='third-party/highcharts/highcharts.js' type="text/javascript"></script>
</body>
</html>