<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
	<meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
	<title>XHProf: Hierarchical Profiler Report</title>

<link href='css/xhprof.css' rel='stylesheet'  type='text/css'></link>
<link href="css/tablesorter.pager.css" rel="stylesheet" type="text/css" />             
<link href='third-party/jquery/jquery.tooltip.css'  rel='stylesheet' type='text/css'></link>
<link href='third-party/jquery/jquery.autocomplete.css'  rel='stylesheet' type='text/css'></link>
<?php
if (isset($_xh_header))
{
    echo $_xh_header;
}
?>
</head>
<body>
 <div class="dash-header">
   <div class="search">
       <form name="simple_bar" method="get" action="">      
          Search: <input type="text" name="run" size="25" />
          <input type="submit" value="Go" name="submit" class="form-button" />
       </form>
   </div>
   <div class="search">
       <form name="simple_bar" method="get" action="">      
          Filter Domain: 
		  <select name="domain_filter">
<?php
foreach($domainFilterOptions as $server)
{
    if($server == $domainFilter)
    {
	echo "<option value=\"{$server}\" selected=\"selected\">$server</option>\n";
    }else
    {
	echo "<option value=\"{$server}\">$server</option>\n";
    }
}

?>
		  </select>
          <input type="submit" value="Apply" name="submit" class="form-button" />
       </form>
   </div>
      <div class="search">
       <form name="simple_bar" method="get" action="">      
          Filter Server: 
		  <select name="server_filter">
<?php
foreach($serverFilterOptions as $server)
{
    if($server == $serverFilter)
    {
	echo "<option value=\"{$server}\" selected=\"selected\">$server</option>\n";
    }else
    {
	echo "<option value=\"{$server}\">$server</option>\n";
    }
}

?>
		  </select>
          <input type="submit" value="Apply" name="submit" class="form-button" />
       </form>
   </div>
   <div class="link-options">
      Last &nbsp;<a href="?last=25">25</a> &nbsp;<a href="?last=50">50</a> &nbsp;Runs |
      Most Expensive &nbsp;<a href="?getruns=cpu&amp;days=1">Today</a> &nbsp;<a href="?getruns=cpu&amp;days=7">Past Week</a> |
      Most Ram &nbsp;<a href="?getruns=pmu&amp;days=1">Today</a> &nbsp;<a href="?getruns=pmu&amp;days=7">Past Week</a> |
      Longest Running &nbsp;<a href="?getruns=wt&amp;days=1">Today</a> &nbsp;<a href="?getruns=wt&amp;days=7">Past Week</a>
   </div>
   <h1 class="xh-title"><a href="?">XH GUI</a></h1> 
 </div>  