<table id="box-table-a" class="tablesorter" summary="Stats">
<thead>
    <tr>
        <th>Function</th>
        <th>Call Count</th>
        <th>Wall Time</th>
        <th>CPU</th>
        <th>Memory Usage</th>
        <th>Peak Memory Usage</th>
        <th>Exclusive Wall Time</th>
        <th>Exclusive CPU</th>
        <th>Exclusive Memory Usage</th>
        <th>Exclusive Peak Memory Usage</th>
    </tr>
</thead>
<tbody>
    <?php
    foreach($flat_data as $element)
    {?>
    
    <tr>
        <td><a href="?run=<?= $run1; ?>&amp;symbol=<?=urlencode($element['fn']); ?>"><?= htmlentities($element['fn'], ENT_QUOTES, 'UTF-8'); ?></a></td>
        <td><?= $element['ct']; ?></td>
        <td><?= $element['wt']; ?></td>
        <td><?= $element['cpu']; ?></td>
        <td><?= $element['mu']; ?></td>
        <td><?= $element['pmu']; ?></td>
        <td><?= $element['excl_wt']; ?></td>
        <td><?= $element['excl_cpu']; ?></td>
        <td><?= $element['excl_mu']; ?></td>
        <td><?= $element['excl_pmu']; ?></td>
    </tr>
    <?php
    }
    ?>
</tbody>
</table>