<table id="box-table-a" class="tablesorter" summary="Stats">
<thead>
    <tr>
        <td>Function</td>
        <td>Call Count</td>
        <td>Wall Time</td>
        <td>CPU</td>
        <td>Memory Usage</td>
        <td>Peak Memory Usage</td>
        <td>Exclusive Wall Time</td>
        <td>Exclusive CPU</td>
        <td>Exclusive Memory Usage</td>
        <td>Exclusive Peak Memory Usage</td>
    </tr>
</thead>
<tbody>
    <?php
    foreach($flat_data as $element)
    {?>
    <tr>
        <td><a href="?run=<?= $run1; ?>&amp;symbol=<?=urlencode($element['fn']); ?>"><?= htmlentities($element['fn'], ENT_QUOTES, 'UTF-8'); ?></a></td>
        <td><?= $element['ct']; ?></td>
        <td><?= $element['wt']; ?></td>
        <td><?= $element['cpu']; ?></td>
        <td><?= $element['mu']; ?></td>
        <td><?= $element['pmu']; ?></td>
        <td><?= $element['excl_wt']; ?></td>
        <td><?= $element['excl_cpu']; ?></td>
        <td><?= $element['excl_mu']; ?></td>
        <td><?= $element['excl_pmu']; ?></td>
    </tr>
    <?php
    }
    ?>
</tbody>
</table>