<div id="container"></div>
<table id="box-table-a" class="tablesorter" summary="Stats">
<thead>
    <tr>
    	<th>Timestamp</th>
        <th>Call Count</th>
        <th>Wall Time</th>
        <th>CPU</th>
        <th>Memory Usage</th>
        <th>Peak Memory Usage</th>
        <th>Exclusive Wall Time</th>
        <th>Exclusive CPU</th>
        <th>Exclusive Memory Usage</th>
        <th>Exclusive Peak Memory Usage</th>
    </tr>
</thead>
<tbody>
<?php while ($data = XHProfRuns_Default::getNextAssoc($rs)) {?>
    <tr>
        <td>
            <?php echo date('Y-m-d H:i:s', $data['timestamp']) ?><br />
            <?php echo $data['id']?>
        </td>
        <td><?php echo $data['ct'] ?></td>
        <td><?php echo $data['wt'] ?></td>
        <td><?php echo $data['cpu'] ?></td>
        <td><?php echo $data['mu'] ?></td>
        <td><?php echo $data['pmu'] ?></td>
        <td><?php echo $data['excl_wt'] ?></td>
        <td><?php echo $data['excl_cpu'] ?></td>
        <td><?php echo $data['excl_mu'] ?></td>
        <td><?php echo $data['excl_pmu'] ?></td>
    </tr>
<?php } ?>
</tbody>
</table>