<?php
        $arrayOfTotal = array();
        $i=0;
        foreach ($metrics as $metric) {
           
          $arrayOfTotal[$i]["label"]  = "Display run ". str_replace("<br>", " ", stat_description($metric));
          $arrayOfTotal[$i]["value"]  = number_format($totals[$metric]) .  " ". $possible_metrics[$metric][1];
          $arrayOfTotal[$i]["metric"] = $possible_metrics[$metric][1];  
          $i++;
        } 
        if ($display_calls) {
            $format_total= number_format($totals['ct']);
        }
 
    //TODO This is lame
    global $comparative;   
    ?>
<div id="view-center-tables">    
   <div id="run-id-wrapper">
      <h2 class="run-details">RunID: <?=$xhprof_runs_impl->run_details['id']; ?> against <?=$xhprof_runs_impl->run_details['server name'];?><?=$xhprof_runs_impl->run_details['url']; ?> </h2>
      <a href="callgraph.php?run=<?=$xhprof_runs_impl->run_details['id']; ?>" class="callgraph">View Callgraph</a>
   </div>
    <div id="left-col"> 
     <div>   
     <table id="box-table-b">
     <thead>
        <tr><th>Stat</th><th>Exact URL</th><th>Similar URLs</th></tr>
     </thead>
     <tbody>
        <tr><td>Count</td><td><a href="/?geturl=<?=urlencode($comparative['url']['url']);?>"><?=$comparative['url']['count(`id`)'];?></a></td><td><a href="/?getcurl=<?=urlencode($comparative['c_url']['url']);?>"><?=$comparative['c_url']['count(`id`)'];?></a></td></tr>
        <tr><td>Min Wall Time</td><td><?=number_format($comparative['url'] ['min(`wt`)']) . " " . $arrayOfTotal[0]["metric"];?></td><td><?=number_format($comparative['c_url']['min(`wt`)']) . " " . $arrayOfTotal[0]["metric"];?></td></tr>
        <tr><td>Max Wall Time</td><td><?=number_format($comparative['url']['max(`wt`)']) . " " . $arrayOfTotal[0]["metric"];?></td><td><?=number_format($comparative['c_url']['max(`wt`)']) . " " . $arrayOfTotal[0]["metric"];?></td></tr>
        <tr><td>Avg Wall Time</td><td><?=number_format($comparative['url']['avg(`wt`)']) . " " . $arrayOfTotal[0]["metric"];?></td><td><?=number_format($comparative['c_url']['avg(`wt`)']) . " " . $arrayOfTotal[0]["metric"];?></td></tr>
        <tr><td style="font-weight: bold;"><?php echo $arrayOfTotal[0]["label"]; ?></td><td style="font-weight: bold;"><?php echo $arrayOfTotal[0]["value"]; ?></td><td>&nbsp;</td></tr>
        <tr><td>Min CPU Ticks</td><td><?=number_format($comparative['url']['min(`cpu`)']) . " " . $arrayOfTotal[0]["metric"];?></td><td><?=number_format($comparative['c_url']['min(`cpu`)']) . " " . $arrayOfTotal[0]["metric"];?></td></tr>
        <tr><td>Max CPU Ticks</td><td><?=number_format($comparative['url']['max(`cpu`)']) . " " . $arrayOfTotal[0]["metric"];?></td><td><?=number_format($comparative['c_url']['max(`cpu`)']) . " " . $arrayOfTotal[0]["metric"];?></td></tr>
        <tr><td>Avg CPU Ticks</td><td><?=number_format($comparative['url']['avg(`cpu`)']) . " " . $arrayOfTotal[0]["metric"];?></td><td><?=number_format($comparative['c_url']['avg(`cpu`)']) . " " . $arrayOfTotal[0]["metric"];?></td></tr>
        <tr><td style="font-weight: bold;"><?php echo $arrayOfTotal[1]["label"]; ?></td><td style="font-weight: bold;"><?php echo $arrayOfTotal[1]["value"]; ?></td><td>&nbsp;</td></tr>
        <tr><td>Min Peak Memory Usage</td><td><?=number_format($comparative['url']['min(`pmu`)']) . " " . $arrayOfTotal[3]["metric"];?></td><td><?=number_format($comparative['c_url']['min(`pmu`)']) . " " . $arrayOfTotal[3]["metric"];?></td></tr>
        <tr><td>Max Peak Memory Usage</td><td><?=number_format($comparative['url']['max(`pmu`)']) . " " . $arrayOfTotal[3]["metric"];?></td><td><?=number_format($comparative['c_url']['max(`pmu`)']) . " " . $arrayOfTotal[3]["metric"];?></td></tr>
        <tr><td>Avg Peak Memory Usage</td><td><?=number_format($comparative['url']['avg(`pmu`)']) . " " . $arrayOfTotal[3]["metric"];?></td><td><?=number_format($comparative['c_url']['avg(`pmu`)']) . " " . $arrayOfTotal[3]["metric"];?></td></tr>
        <tr><td style="font-weight: bold;"><?php echo $arrayOfTotal[3]["label"]; ?></td><td style="font-weight: bold;"><?php echo $arrayOfTotal[3]["value"]; ?></td><td>&nbsp;</td></tr>
        <tr><td style="font-weight: bold;">Number of Function Calls:</td><td style="font-weight: bold;"><?php echo $format_total; ?></td><td>&nbsp;</td></tr>
        <tr><form method="get" action="/"><input type="hidden" name="run1" value="<?=$xhprof_runs_impl->run_details['id']; ?>">
            <td style="font-weight: bold;">Perform Delta:</td>
            <td><input type="text" name="run2"></td>
            <td><input type="submit" value="Delta"></td>
        </tr>
      </tbody>
    </table>
  </div>
 </div>
 
 <div id="right-col">
  <div class="box-fix">
   <table class="box-tables">
    <thead>
     <tr><th>Cookie</th><th>Results</th></tr>
    </thead>
   <tbody>
  <?php
    $cookieArr =  unserialize($xhprof_runs_impl->run_details['cookie']);
 // echo '<pre>'.print_r($cookieArr, true).'</pre>';        
    foreach($cookieArr as $key=>$value){
        if (is_array($value))
        {
            $value = implode(", ", $value);
        }
        echo "<tr>\n";
        echo "\t<td>" . $key . "</td><td>" . chunk_split($value) . "</td>\n";
        echo "</tr>\n";
     }
  ?>
   </tbody>
  </table>
 </div>
 <div class="box-fix-cr">
  <table class="box-tables">
    <tr><th>Get</th><th>Results</th></tr>
   <tbody>
  <?php
    $getArr =  unserialize($xhprof_runs_impl->run_details['get']);
 // echo '<pre>'.print_r($getArr, true).'</pre>';         
    foreach($getArr as $key=>$value){       
        echo "<tr>";
        echo "<td>" . $key . "</td><td>" . $value . "</td>";
        echo "</tr>";
     }
  ?>
   </tbody>
  </table>
 </div>
 <div class="box-fix-cr">
   <table class="box-tables">
    <tr><th>Post</th><th>Results</th></tr>
    <tbody>
  <?php
     $postArr =  unserialize($xhprof_runs_impl->run_details['post']);
  // echo '<pre>'.print_r($postArr, true).'</pre>';       
    foreach($postArr as $key=>$value){        
        echo "<tr>";
        echo "<td>" . $key . "</td><td>" . $value . "</td>";
        echo "</tr>";
     }
  ?>
    </tbody>
   </table>
  </div>
  
 </div>
 
</div>